# Generated by Django 4.0.1 on 2022-06-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de categoría')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cliente', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Cliente')),
                ('usuario', models.CharField(max_length=20, verbose_name='Usuario')),
                ('producto', models.CharField(max_length=20, verbose_name='Productos')),
                ('promociones', models.CharField(max_length=20, verbose_name='Promociones')),
                ('descuentos', models.CharField(max_length=20, verbose_name='Descuentos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
